// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("ExcelProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("ExcelProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library implements a read-only Excel type provider for Net Standard 2.0.")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "ExcelProvider.Runtime"

    [<Literal>]
    let AssemblyProduct = "ExcelProvider"

    [<Literal>]
    let AssemblyDescription =
        "This library implements a read-only Excel type provider for Net Standard 2.0."

    [<Literal>]
    let AssemblyVersion = "3.0.0"

    [<Literal>]
    let AssemblyFileVersion = "3.0.0"
