// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ExcelProvider")>]
[<assembly: AssemblyProductAttribute("ExcelProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing a Excel type provider.")>]
[<assembly: AssemblyVersionAttribute("0.9.2")>]
[<assembly: AssemblyFileVersionAttribute("0.9.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ExcelProvider"
    let [<Literal>] AssemblyProduct = "ExcelProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing a Excel type provider."
    let [<Literal>] AssemblyVersion = "0.9.2"
    let [<Literal>] AssemblyFileVersion = "0.9.2"
